### PR TITLE
UMCU changes

### PR DESCRIPTION
**Pull request by sandertan**
Hi @piekvossen and @vanboefer (hi Jenia nice to work with an old-colleague again! )

I made a few changes to the pipeline to get the pipeline to run at our site. It might be nice to put these in the main code base. 

Summary of changes:
- Drop rows containing empty values in the text column. The anonymizer crashed on this.
- Add documentation on how to run the pipeline in offline mode with cached models
- Add option to configure a different encoding for the input file
- Flush print statements before doing the intensive operations (from https://stackoverflow.com/questions/230751/how-can-i-flush-the-output-of-the-print-function)
- Small fix to example run command in documentation

### CODE REVIEW

**Comment by vanboefer** [comment]
Hi @sandertan! Nice that our paths cross again :) Thanks for the pull. 

Do you get correct output when you run the pipeline (if you run it on the example file, do you get the output that we have in the repo)? I was getting wrong predictions when using the model on hugging face (see the issue I opened [here](https://github.com/ThilinaRajapakse/simpletransformers/issues/1282)), but I did not have time to fix it before I went on vacation.

**Comment by sandertan** [comment]
Hi @vanboefer , I'm also getting only zeros in the output of the example file.

@piekvossen fyi

**Comment by vanboefer** [comment]
Hi @sandertan (and @piekvossen)!
The "hacky" solution that can be used in the meantime is changing the last part of the function `predict_levels` in [icf_classifiers.py](https://github.com/cltl/aproof-icf-classifier/blob/main/src/icf_classifiers.py) to the following:
```
# predict
_, raw_outputs = model.predict(to_predict)
predictions = np.squeeze(raw_outputs)
return pd.Series(predictions, index=text.index)
```
When I'm back at the beginning of November, I will try to find a solution that fixes the incorrect setting on HuggingFace.

**Comment by sandertan** [comment]
@vanboefer Indeed that solves the all zeros issue. For the test I'm now getting the expected output.

**Pull request merged**
